spring:
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.200.131:3306/shiro?autoReconnect=true&useSSL=false&characterEncoding=utf-8
  redis:
    host: jdbc:mysql://192.168.200.131:6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true